server:
  port: 8080

spring:
  profiles:
    active: dev

logging:
  level:
    com.supermarket: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: supermarketSecretKey1234567890SupermarketSecretKey
  expiration: 86400000